"""API response mapping for runtime turn outputs."""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from agentium.core.agent_runtime import RuntimeResult


class RuntimeTurnResponse(BaseModel):
    """Stable response shape for runtime turn APIs.

    Attributes:
        status: Runtime turn status string.
        tool_name: Executed or requested tool name.
        output: Optional tool output for completed turns.
        tool_use_id: Optional tool execution id.
        approval_id: Optional approval id for pending turns.
        error_code: Optional machine-readable error code.
        message: Optional human-readable message.
        references: Optional structured source anchors for research-style turns.
        logic_summary: Optional short reasoning summary for research profile.
        confidence: Optional calibrated confidence hint (0–1 or profile-specific).
    """

    status: str = Field(min_length=1)
    tool_name: str = Field(min_length=1)
    output: Optional[Dict[str, Any]] = None
    tool_use_id: Optional[str] = None
    approval_id: Optional[str] = None
    error_code: Optional[str] = None
    message: Optional[str] = None
    references: List[Dict[str, Any]] = Field(default_factory=list)
    logic_summary: Optional[str] = None
    confidence: Optional[float] = None

    class Config:
        """Pydantic model configuration."""

        extra = "forbid"


def map_runtime_result_to_response(result: RuntimeResult) -> RuntimeTurnResponse:
    """Map runtime result to stable API response object.

    Args:
        result: Runtime result generated by AgentRuntime.

    Returns:
        RuntimeTurnResponse: API-safe normalized response payload.
    """

    return RuntimeTurnResponse(
        status=result.status.value,
        tool_name=result.tool_name,
        output=result.output,
        tool_use_id=result.tool_use_id,
        approval_id=result.approval_id,
        error_code=result.error_code,
        message=result.message,
        references=[],
    )

